language: node_js
node_js:
  - 8

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - stage: 'Tests'
      name: 'Tests'
      script:
        - yarn commitlint-travis
        - yarn lint:js
        - yarn lint:hbs
        - yarn test
        - yarn ember ts:precompile

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: 'Additional Tests'
      env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=fastboot-addon-tests

    - stage: 'Release'
      script: yarn semantic-release
      if: branch = master
    - script: yarn ember deploy production
      if: branch = master OR env(TRAVIS_TAG) is present

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
